name: Flask App Tests

on:
  pull_request:
    branches: [main]

jobs:

  # Set up operating system to test virtually
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.13"]

    # Secrets/env variables go here - read from github secrets
    env:
      EXAMPLE_ENVIRONMENT_VARIABLE: ${{ secrets.EXAMPLE_ENVIRONMENT_VARIABLE }}

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout repository code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Step 3: Install dependencies - notice use of pyproject toml groups instead of requirements
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      # Step 4: Add any debugging information we want to see
      - name: Print debugging information
        run: |
          echo "Python Version: $(python --version)"
          echo "Working Directory: $(pwd)"
          echo "Contents of Working Directory: $(ls -l)"

     # Step 4: Run Tests 
     # (pytest .) instructs pytest test framework to discover and execute tests within current and subdirectories.
      - name: Run pytests
        run : pytest .